
name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t anassk1234/next-js-app2
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u anassk1234 --password-stdin 
    - run: docker push anassk1234/next-js-app2:latest